### ISSUE TITLE
Custom Parameters for Custom Operations

### ISSUE THREAD

**Issue by jtravan3** [Asymmetrik/node-fhir-server-core#171] opened 2019-05-13 14:53 UTC
### Do you want to request a feature, report a bug, or improve documentation?

This is a new feature that will add the ability to add custom parameters for custom operations.

For example, I currently have
```
/Medication/:id/$sig?code=AgeInDays|2200
```
with the config being
```
{
	name: 'sig-by-ndc',
	route: '/:id/$sig',
	method: 'GET'
}
```
I would like to be able to support
```
/Medication/:id/$sig?AgeInDays=2200
```
Currently the `metadata` configuration is only supported at the route level and not the operation level.

**Comment by navndn** [comment] 2019-05-13 18:02
I had assumed custom searchParams would work on operations as well. Inability to add custom params really handicaps the Custom Operations feature.  
 
Hello @jtravan3 , any thoughts on target release/timeline for this feature or how hard it is to implement given metadata config is already available for Resource routes (I'm new to this project. Trying things out since 2 weeks).

Thanks!

**Comment by navndn** [comment] 2019-05-13 18:30
Not exactly related.. Custom Operations defined for individual Resources are not being listed under their corresponding Resource in `CapabilityStatement` of `/metdata` response.  

Example: 
My profiles' config looks like this

```
		[RESOURCES.PATIENT]: {
			service: './app/services/patient/patient.service.js',
			versions: [ VERSIONS['4_0_0'], VERSIONS['3_0_1'] ],
			metadata: path.resolve('./app/services/patient/patient.metadata.js'),
			operation: [{
				name: 'everything',
				route: '/$everything',
				method: 'GET',
				reference: 'https://www.hl7.org/fhir/patient-operation-everything-inline.html'
			}, {
				name: 'everything-by-id',
				route: '/:id/$everything',
				method: 'GET',
				reference: 'https://www.hl7.org/fhir/patient-operation-everything-inline.html'
			}]
		},

```

Response from `http://localhost:3000/4_0_0/metadata`

```
{
    "resourceType": "CapabilityStatement",
    "status": "active",
    "date": "2019-05-13T12:31:41-04:00",
    "publisher": "Not provided",
    "kind": "instance",
    "software": {
        "name": "FHIR Server",
        "version": "1.4.0"
    },
    "implementation": {
        "description": "FHIR Test Server (R4)"
    },
    "fhirVersion": "4.0.0",
    "format": [
        "application/fhir+json"
    ],
    "rest": [{
        "mode": "server",
        "resource": [{
                "type": "Patient",
                "profile": {},// snipped
                "interaction": [],// snipped
                "searchInclude": [],// snipped
                "searchParam": []// snipped
            },
            {} // snipped
        ],
        "operation": [{
                "name": "everything",
                "definition": {
                    "reference": "https://www.hl7.org/fhir/patient-operation-everything-inline.html"
                }
            },
            {
                "name": "everything-by-id",
                "definition": {
                    "reference": "https://www.hl7.org/fhir/patient-operation-everything-inline.html"
                }
            }
        ]
    }]
}
```

I was expecting the operations `everything` and `everything-by-id` to be listed at `rest.resource.[x].operation` but they are available at `rest.operation` instead. Is this expected behaviour?

Thanks

**Comment by jtravan3** [comment] 2019-05-13 18:31
It shouldn't be a huge effort to get this added. I planned to work on it as soon as this issue was agreed upon. I would say less than a week once I got started.

**Comment by navndn** [comment] 2019-05-13 18:43
Did you mean you have added this feature already? Is this available on some branch?

**Comment by jtravan3** [comment] 2019-05-13 18:45
No, this is not added yet but I can begin working on a PR.

**Comment by Robert-W** [comment] 2019-05-13 19:26
Hey @jtravan3, this sounds pretty good to me. Would you be able to fork off the `feat/version_2_0_0` branch. We have two PR's up now and have a review to get these and released tomorrow morning.  2.0.0 has significant changes and we would prefer new features start in that branch (we do plan to maintain non 2.0.0 branches so we can retrofit it there as well if people do not want to upgrade to 2.0.0).

We have even been internally thinking of ways we can support this. One was to pass in optional arguments in the config and then just mixing them in with the defaults. 

Another, which works currently in 2.0.0 by default, is that 2.0.0 now passes the original request through to services, meaning you can use our sanitized args, or, you can grab the raw args from the request.  So for example, in 2.0.0, you can do the following for your use case where your config looks like this:

```javascript
{
  name: 'sig-by-ndc',
  route: '/:id/$sig',
  method: 'GET'
}
```
Your service could looks something like this:

```javascript
module.exports.sigByNdc = (args, context) => {
  let { req } = context;
  let AgeInDays = req.query.AgeInDays; // for GET, for a POST, use req.body.AgeInDays instead
};
```

However in 2.0.0, this would allow you to access any parameters you desire, but there would need to be more work to ensure it shows up in the capability statement in the appropriate section.

@navndn As for the capability statement, I will need to check on that and get back to you. I have been a little pre occupied trying to get everything ready for Seattle dev days, new releases, and some infrastructure related items.

**Comment by jtravan3** [comment] 2019-05-13 19:49
If that is supported in 2.0.0 then we will probably wait and upgrade when released.

**Comment by navndn** [comment] 2019-05-14 05:28
@Robert-W , Got it. Thanks. 


> We have even been internally thinking of ways we can support this. One was to pass in optional arguments in the config and then just mixing them in with the defaults.

Assuming you are referring to possibility of configuring custom args in Operations config and mixing them  with core-server's default searchParams.  Shouldn't these new args be mixed with the custom metadata (which overrides server-core's), instead?

**Comment by Robert-W** [comment] 2019-05-14 19:10
@navndn It would need to be able to work in both cases. If a developer is not providing custom metadata functionality, I would still like the additional custom parameters to be visible in the default capability statement in the appropriate place so the server can still be conformant.

If they added a handler for custom metadata, custom arguments should be added to that as well. Internally we may need to shuffle things around to make it easier to implement the custom `makeResource` case, where they can pull in all the default and configured parameters.  Although, I think the original case for custom `makeResource` was to document custom params.  Allowing custom params to be configurable and populating the capability statement may alleviate the need for `makeResource` functionality.

**Comment by Robert-W** [comment] 2019-05-14 19:11
@jtravan3 2.0.0 will be released tomorrow am.

**Comment by Robert-W** [comment] 2019-05-15 13:32
Ok it's released, feel free to check it out. There is a migration guide here, https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/MIGRATION_2.0.0.md

**Comment by jjosef** [comment] 2019-05-17 14:00
I had to mess with this a little bit, so I think its worth looking into a better solution for this.

Consider this code, a bit hacky, but it works:
in my metadata file:
```js
import { resolveSchema } from '@asymmetrik/node-fhir-server-core'
import { getSearchParams } from '@asymmetrik/node-fhir-server-core/src/server/utils/conformance.utils'

export const makeResource = args => {
  const Resource = require(resolveSchema(args.base_version, args.key))
  const searchParams = getSearchParams(args.key, args.base_version)

  // Return our conformance statement
  return {
    type: Resource.resourceType,
    profile: {
      reference: `http://hl7.org/fhir/${args.key}.html`
    },
    conditionalDelete: 'not-supported',
    searchParam: searchParams.concat([
      {
        name: '_count',
        type: 'number',
        documentation: 'The number of results to return'
      },
      {
        name: 'AgeInDays',
        type: 'number',
        documentation: 'Age in days'
      }
    ])
  }
}
```

My profile:

```
    patient: {
      service: path.resolve(__dirname, '../logic/fhir/patient.ts'),
      versions: [VERSIONS[FHIRVERSION]],
      metadata: path.resolve(__dirname, '../logic/fhir/metadata/patient.ts'),
      operation: [
        {
          name: 'everything',
          route: '/$everything',
          method: 'GET',
          reference:
            'https://www.hl7.org/fhir/patient-operation-everything-inline.html'
        }
      ]
    },
```

Both the custom operation and search allowed the custom params. Specifically, it would be nice if either `getSearchParams` was available in the project root, or there was an `appendResource` method instead of `makeResource`

Thoughts on this implementation?

**Comment by Robert-W** [comment] 2019-05-17 15:23
Yea so I think currently this is the only way to actually achieve this and it is a bit hacky.  I also agree the name can be a little misleading but I am hesitant to change the name since that would break any current implementations (simple change but would be annoying none the less). We do plan to expose a simple way to require arguments used, e.g. move `getSearchParams` to top level export, so that should be coming soon.

We are definitely open to suggestions but would really like to do things in a backwards compatible way, and preferably in a way that can reduce the amount of code written by the end developer and/or be useful for generic tools built on top of this library.

One idea we played with was to pass args in the config, so something like this:

```javascript
let config = {
  // Global, applies to all resources
  args: {
    _count: {
      type: 'number',
      // we use fhirtype because we generate this code for mulitple targets, type 
      // refers to the type for the target and fhirtype is what is in the spec, for JS,
      // this does not matter, but in GraphQL, you'll see things like,
      // type: GraphQLString, fhirtype: 'string' 
      fhirtype: 'number',
      definition: '<uri-to-definition>',
      description: 'The number of results to return'
    }
  },
  profiles: {
    patient: {
      // Only applies to patient resources
      args: {
        AgeInDays: {
          type: 'number',
          fhirtype: 'number',
          definition: '<uri-to-definition>',
          description: 'The patients age in days'
        }
      }
    }
  }
};
```

With this approach, the idea is that a user specifies them here for all profiles or individual ones. Then, in core, we would add these to the appropriate places in the metadata. We also could do sanitization/type checking on these, so the sanitized args coming through would contain your custom args. This would also work with some of the query builders (we have a mongo one but will add more in the future).

**Comment by jjosef** [comment] 2019-05-17 15:50
I like the idea of it being at the config level

**Comment by luan-dev** [comment] 2021-11-16 17:35
Closing stale issue. Please raise a new issue if this is still a problem

**Closed by luan-dev** 2021-11-16 17:35 UTC
Labels: enhancement

**Comment by Radhika-B1** [comment] 2023-11-16 06:51
when run yarn i got issue like 
 @asymmetrik/fhir-gql-schema-utils:test
 >i install this package ,but still showing this issue 
  Cannot find module 'graphql' from 'index.test.js'<
      Cannot find module 'sequelize' from 'index.js'
Can you this issue how to resolve
